# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: ehV9r4lr8jhixIIAcvPsIividr8+tKj6YiE6P7AyNJuLHmc3wU+yRZfuxER4ftmrQAda0iDML064StTTyWo8cxMLE/ok0jXfx6DQGi0FwhEIyNOxMYkjNESLZwVeWWH9R8Ym4zIlbOmGjJdnLpvLIX01Dc/zovh50xEKQDmUooHw5W5GNQ8sFglDVJYnU//Lu+pl4iPClJdzaJM1Bl2Nt04xqRzyIqegcrxNttnx79VVYy/OpjNPeoS/13sU53UHEiMSKnLI5t9mqQJ64IKv3SrJVBtdHPl3ZLxRzaRrCa1twnjxtz9+UYU4jBHpNI9RIW0ny00PRT+VcOk5KI+CTb1L11XOuVpI3BEsr1X973UlkkF4EYEfEtRkj5LWL9G+MOydNdJuTznqITdzuqt+4cy0dtd7MSB8SC/zAZcJQmIGWlpfI0sowVkR29OqZkrpu3tIfR8tFs/kgcM5J1Zae60wlMc9qmMbqvLQ4se8rjvuNjIHxqyL0SLV1xhfo3BgQ4Uby6qyJsGolbXqW6tMdZc/409z0KcXvWx9x2BZKVL1iLn4uM6nZ/yp6z9TZSCP0L9EycgoHYrRsTr1C8TxJ/NLsipEqVJrtdq0SAkuHczOcfDllrx/rkDLTHi2OrNEfYF8CSonV7ehtzjjfbd/7ufyLkr0uvGRyMgpvkAGWa0=
    # SAUCE_TOKENS
    - secure: XNHOUvnRJj3mmkxz2eUz43xbPSMRFtsVeGpFApAxcI5VSPgY8yKrilnFRcyA0pXxIvq0xvbwfOc9n5iCKsRLDb7HzSxxH9xsksw9xFYCfAc8sc3u/3uWCBpfZaKADd/y1OBQBRcDxaPdQjm7hHF4BvoJHzkqWncssx8mW1qtXldxMM2q1yQg0y5eYu0X/jA0V+L30JcDu1Z/dFULDXrcnf/4r2lkdE6raSfFtJa1ryU4dJWFcyUrSeBpsKY2XPQRefNgnD/DbQfKzSbtsQ6olYumj/Kp2uelLbKZ48j24klUw4L7DTs+fwwWsJfNp2RlZJc5dkTkv7sHTLQ1SYGntLWeHNdMY6myV0zoLcvgc+ak7Y66bxT0KQP/AeZSxglRO5BuFDMOTWWfWcPxEuPeEA6Rt1xeUTyrySgHs336fgRxXK6cbi8NlFcAaInX0w7G/fZX54ph0aIIRFKEDG7gQcRvyb5FnA7PNLo1Yuw+1jzs6/f2FW7JuA68+aOV4MZT1afWn+lSjii3X1CkPXfWmg0mqcM0FeD/A551/FZ/HwTf7Xi3vqHwa3wb5oNlsK0CmK6c1Pfhgiz2yf0tfUEshDZV8IuwxiJGEDjzi7UHYl5RSR1Odo/bFzdGooqsa2VQXMQI3XeyRWH4V0WNARQIIYUhQRiY7Ys/qQk68pM94IM=
    - secure: DtT5Acql/DZKpaJZk+sr9fRqvBNooFQSvKdYwFxBDw3kkHn9x3xKNcyUpmxfcZuRTGep7yxNknnE9HbGdyy2dV556ekupqWFSPlr4wRxSgO6iU7uy6XX3BlCB+k3mDwlnrRFQbYglJ0RBSWgtyXSSjdoYWnmJ+jt4eepYFFgCd/GdqwTMamkCVv8sSyVFbg7xWbCye+nEaa5svHQvCWu84OkiI9Ny3FJW7q0BAX6Y2YzrtcVfaVM4c3n4nLYOJV2ygOUzGYCKw0iqkufCHWqN1GOfobnNIcV4M4Or1ZA0BYZefzznY8LOrqnveCnHk1BSWaUKg9wM/asUhGxuw7jvr4+AVEn+GtAEUDzze7jsN1qXo2BsyLNten/6SHl18xzCAotQmorEMFPhBEsRMuDqLeTfi5F8GTAqhmQlSNBtAKLHkkAoo4va964xCkIPWXE+QXBj82GYwtPAlvTns+zJkN+0NG0HLunap/tQsSt94QwbSiggKihl2jK4Umgb8guxCJw2xw27hNSz5+Yq+VCExApnKUi6/n3V+rQ7rHyM3Mz5CXaHyw84cvQvReso4RaHkx9hBeqlq7m2K+ZZm0G9Ts+vy6gnZcc6XhOYsEI8ad5r6xgnjaSCQ9I/Zs98p1GjruJ4Z3VfLi0fkPGku3mHixamzoNsgFNO16NCbnXbsk=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: AyYicDz0oVXa3b2zhMeYhS/N9HpvtgQcqdJC7GOeK6VUUU1UEQ+Ae+JvZ4aObCL0i8H0XvXb5I2CMl43zFZaMrFJfVhzjjMVa+hb1b2my5z2jJcUXiNgIzpZfcQruZVwJgPp376+uquAUOjHyNpD6peqOaftMjmd0JT3JKrWs3hLHlC/sBeHtkt3n4oFZpRUdXj/TR2ugwdv7MxTsdJpqJkwkODJ5vIIJbh630tqajv6r5+yZv1iXjgipG4FjwiaUEZMKf/7EPu4ZqBS35G9zXgiK6kZnEFIPfz4Tkoomj1HharrwR9Tb60X5W5VlYxpPI6+oLn6vja/E9i05Ztj0MVjWYygt348ymy/w8DCShwoA2NayoKTEAUIj4t4NYs78Tl+YfzI5OlnaObThnjdCTvIBdJxLClU/S4vzp+a9CvlCWxbhHu5ZRVE8mAyW+5+4pG1LJyj0b0CmisBlzEEmzg4dJDbGkKUrDBG1kzOgRexjC+k4JjZ7rsMzZDcsM0i27T2/mf8eCeCZhwAfKgiNQqQ8RKQ67dTmmma//TF/tT/ZvNEsVdw+g7LexhwAy13/ZSSBfuuQ/C3oz1alzup/clkLzeTpWEfiDgt1CSDOE0iGzQCp2SeZdbsBfhe/3RWbrwpp//GdJCOPjpQHAPhAWAX4iJGsnhJhCzIDC08+kY=
